config/routes.rb
Raceonline::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    delete '/sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
    get '/sign_in', to: 'devise/sessions#new', as: 'sign_in'
    get '/sign_up', to: 'devise/registrations#new', as: 'sign_up'
    get '/reset_password', to: 'devise/passwords#new', as: 'reset_password'
    get '/user/account', to: 'devise/registrations#edit', as: 'account'
  end

  root 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_favicons.html.erb
<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>
<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>
<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>
<%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
<%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>

app/views/application/_google_analytics.html.erb
<% if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41605507-1', 'raceonline.lt');
    ga('send', 'pageview');
  </script>
<% end %>

app/views/home/index.html.erb
<h1>raceonline.lt</h1>
<p>Greitai čia bus naujoji raceonline.lt versija!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>raceonline.lt - lenktynių rezultatai gyvai</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="description" content="Automobilių sporto lenktynių rezultatai internete!">
    <meta name="author" content="Giedrius Rimkus, Giedrius Šileikis, Darius Šileikis">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= render 'favicons' %>
    <%= render 'google_analytics' %>
  </head>
  <body>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Race Online</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to t('Sign out'), sign_out_path, :method => :delete, :class => 'btn btn-danger' %></li>
              <% else %>
                <li><%= link_to t('Sign up'), sign_up_path %></li>
                <li><%= link_to t('Sign in'), sign_in_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Meniu</li>
              <li><%= link_to 'Apie mus', '#'  %></li>
            </ul>
          </div>

        </div>
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>
          raceonline.lt &copy; 2013.
          <a href="http://www.facebook.com/raceonline.lt" target="_blank"><span class="icon-facebook-sign"></span></a>
          <a href="http://www.facebook.com/dirtrally" target="_blank"><span class="icon-facebook-sign"></span></a>
          <a href="https://twitter.com/raceonlinelt" target="_blank"><span class="icon-twitter-sign"></span></a>
        </p>
      </footer>

    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>